name: Rescue
version: '1.2'
main: shaman.rescue.Rescue
author: Shaman
description: Plugin for spawn teleport via site
website: 'https://letnicraft.ru'
commands:
  rescue:
    description: Command for spawn teleport via site
    permission: rescue.usage
