name: Rescue
version: '1.0'
main: io.github.shaman.rescue.Rescue
author: Shaman
description: Plugin for spawn teleport via site
website: 'https://letnicraft.ru'
commands:
  rescue:
    usage: /<command> <игрок>
    description: Command for spawn teleport via site
    permission: rescue.usage
